### ISSUE TITLE
Is it really ok that this repo is public?

### ISSUE THREAD

**Issue by AhnMo** [purelledhand/cure#1]
Sometimes you want somebody to know what you think, but I'm worry about it could be clue of social engineering.

If you don't care about it, just close this issue.

Good luck <(")

**Comment by purelledhand** [comment]
Actually I have a fear for talking my own think, and this is the first step to cure it.
That's why I open this repo for public.
but I really appreciate to your concern. 🙏🏻
Thx to you, I'll be careful not to write something that might be a clue to my social engineering. 😉
